# Numpy

* NumPy stands for Numerical Python and it is an open source project.
* NumPy is a Python library used for working with arrays, linear algebra, fourier transform, and matrices.
* The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.
* NumPy is usually imported under the np alias.

* It's usually fixed in size and each element is of the same type. We can cast a list to a numpy array by first importing numpy.

# 1D Numpy

In [3]:
import numpy as np

In [12]:
# Create a numpy array

a = np.array([0, 1, 2, 3, 4])
a

array([0, 1, 2, 3, 4])

In [13]:
print(np.__version__)

2.5.0


In [14]:
type(a)

numpy.ndarray

In [15]:
a.dtype

dtype('int64')

In [16]:
a.size

5

In [17]:
a.ndim

1

In [18]:
a.shape

(5,)

In [22]:
# Get the mean of numpy array
a.mean()

np.float64(2.0)

In [23]:
# Get the standard deviation of numpy array
a.std()

np.float64(1.4142135623730951)

In [24]:
# Get the biggest value in the numpy array
a.max()

np.int64(4)

In [25]:
# Get the smallest value in the numpy array
a.min()

np.int64(0)

In [26]:
for x in a:
    print(x)

0
1
2
3
4


# 1D Arrays: Vectors

* A 1D array is often termed as a vector.
* Depending upon the orientation of the data, the vector can be classified as a row vector or a column vector.
* Mathematically, we can add, subtract, and take the product of two vectors, provided they are the same shape.

# 2D Arrays : Matrices

* A 2D array is also called a Matrix.
* These are typically rectangular arrays with data stored in different rows.
* All of the operations mentioned above are also applicable to the 2D arrays.

In [1]:
b = [[11, 12, 13], [21, 22, 23], [31, 32, 33]]
b

[[11, 12, 13], [21, 22, 23], [31, 32, 33]]

In [4]:
# Convert list to Numpy Array
# Every element is the same type

B = np.array(b)
B

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [5]:
# Show the numpy array dimensions

B.ndim

2

In [6]:
# Show the numpy array shape

B.shape

(3, 3)

In [7]:
# Show the numpy array size

B.size

9

In [10]:
# Access the element on the second row and third column

B[1, 2]

np.int64(23)

In [11]:
# Access the element on the first row and first column

B[0][0]

np.int64(11)

In [12]:
# Access the element on the first row and first and second columns

B[0][0:2]

array([11, 12])

In [13]:
# Access the element on the first and second rows and third column

B[0:2, 2]

array([13, 23])

In [15]:
X = np.array([[1, 0], [0, 1]]) 
Y = np.array([[2, 1], [1, 2]]) 
Z = X + Y
Z

array([[3, 1],
       [1, 3]])

In [17]:
Z = 2 * Y
Z

array([[4, 2],
       [2, 4]])

In [18]:
Z = X * Y
Z

array([[2, 0],
       [0, 2]])

In [19]:
Z = np.dot(X,Y)
Z

array([[2, 1],
       [1, 2]])

In [20]:
np.sin(Z)

array([[0.90929743, 0.84147098],
       [0.84147098, 0.90929743]])